# Generated by Django 5.1.1 on 2024-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Lessons',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
