# Generated by Django 5.1.1 on 2024-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0002_course_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
