# Generated by Django 5.1.1 on 2024-10-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0003_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_mail', models.CharField(max_length=50)),
                ('student_phone', models.CharField(max_length=10)),
            ],
        ),
    ]
