# Generated by Django 5.1.1 on 2024-10-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0004_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='learnList',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
