# Generated by Django 5.1.1 on 2024-10-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traino', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Requirements',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
